packages/protocol-contracts/contracts/ZetaConnector.base.sol
packages/protocol-contracts/contracts/ZetaNonEth.sol
packages/protocol-contracts/contracts/interfaces/ZetaErrors.sol
packages/protocol-contracts/scripts/deploy-zeta-token.ts
packages/protocol-contracts/test/ZetaConnector.spec.ts
packages/protocol-contracts/test/ZetaNonEth.spec.ts

* Add tests to ZetaNonEth
* Add burnFrom to emit custom Burnt event
* Allow only Connector to mint (remove TSS)

Remove initial mint from ZetaNonEth, add tests

---

packages/example-contracts/contracts/cross-chain-counter/CrossChainCounter.sol
packages/example-contracts/contracts/cross-chain-counter/test/CounterZetaConnectorMock.sol
packages/example-contracts/contracts/cross-chain-message/CrossChainMessage.sol
packages/example-contracts/contracts/cross-chain-warriors/CrossChainWarriors.sol
packages/example-contracts/contracts/cross-chain-warriors/test/CrossChainWarriorsZetaConnectorMock.sol
packages/example-contracts/contracts/multi-chain-swap/MultiChainSwap.base.sol
packages/example-contracts/contracts/multi-chain-swap/MultiChainSwapErrors.sol
packages/example-contracts/contracts/multi-chain-swap/test/MultiChainSwapZetaConnector.sol
packages/example-contracts/contracts/multi-chain-value/MultiChainValue.sol
packages/example-contracts/test/CrossChainCounter.spec.ts
packages/example-contracts/test/CrossChainWarriors.spec.ts
packages/example-contracts/test/MultiChainSwap.spec.ts
packages/example-contracts/test/MultiChainValue.spec.ts
packages/protocol-contracts/contracts/ZetaConnector.base.sol
packages/protocol-contracts/contracts/ZetaConnector.eth.sol
packages/protocol-contracts/contracts/ZetaConnector.non-eth.sol
packages/protocol-contracts/contracts/ZetaInteractor.sol
packages/protocol-contracts/contracts/interfaces/ZetaInterfaces.sol
packages/protocol-contracts/contracts/testing/ZetaReceiverMock.sol
packages/protocol-contracts/scripts/test-zeta-send.ts
packages/protocol-contracts/test/ZetaConnector.spec.ts
packages/protocol-contracts/test/ZetaInteractor.spec.ts

* gasLimit -> destinationGasLimit
* originSenderAddress -> zetaTxSenderAddress
* origin -> source
* sourceTxOriginAddress
* zetaAmount -> zetaValueAndGas

Update contracts naming

---

packages/protocol-contracts/contracts/Zeta.non-eth.sol
packages/protocol-contracts/contracts/ZetaConnector.eth.sol
packages/protocol-contracts/contracts/testing/ZetaInteractorMock.sol
scripts/slither.ts

A few tweaks to improve Slither results.

Improve Slither results

---

packages/protocol-contracts/README.md

- Add readme file to explain some stuff related only to Protocol contracts module

Add readme to protocol module

---

packages/example-contracts/contracts/cross-chain-counter/CrossChainCounter.sol
packages/example-contracts/contracts/cross-chain-message/CrossChainMessage.sol
packages/example-contracts/contracts/cross-chain-warriors/CrossChainWarriors.sol
packages/example-contracts/contracts/multi-chain-value/MultiChainValue.sol
packages/example-contracts/test/CrossChainCounter.spec.ts
packages/example-contracts/test/CrossChainWarriors.spec.ts
packages/example-contracts/test/MultiChainValue.spec.ts

- Add ZetaInteractor interface to all example contracts
- Update require to solidity errors in example contracts

Add zetainteractor and errors to examples

---

README.md
packages/addresses/README.md
packages/example-contracts/README.md

Mentioning that the example contracts are not audited on the readme.

Add not audited contracts disclaimer

---

packages/addresses/src/addresses.helpers.ts
packages/addresses/src/addresses/addresses.athens.json
packages/addresses/src/addresses/addresses.mainnet.json
packages/addresses/src/addresses/addresses.troy.json
packages/example-contracts/contracts/cross-chain-message/CrossChainMessage.sol
packages/example-contracts/contracts/cross-chain-message/test/CrossChainMessageConnector.sol
packages/example-contracts/contracts/cross-chain-warriors/CrossChainWarriors.sol
packages/example-contracts/contracts/cross-chain-warriors/test/CrossChainWarriorsMock.sol
packages/example-contracts/contracts/shared/ZetaEthMock.sol
packages/example-contracts/contracts/shared/ZetaTestContracts.sol
packages/example-contracts/lib/cross-chain-message/CrossChainMessage.helpers.ts
packages/example-contracts/lib/cross-chain-warriors/CrossChainWarriors.helpers.ts
packages/example-contracts/lib/shared/deploy.helpers.ts
packages/example-contracts/scripts/cross-chain-warriors/set-cross-chain-data.ts
packages/example-contracts/scripts/multi-chain-swap/verify-contract.ts
packages/example-contracts/test/CrossChainCounter.spec.ts
packages/example-contracts/test/CrossChainMessage.spec.ts
packages/example-contracts/test/CrossChainWarriors.spec.ts
packages/example-contracts/test/MultiChainSwap.spec.ts
packages/example-contracts/test/test.helpers.ts
packages/protocol-contracts/contracts/ZetaTokenConsumerUniV2.strategy.sol
packages/protocol-contracts/contracts/ZetaTokenConsumerUniV3.strategy.sol
packages/protocol-contracts/contracts/interfaces/ZetaInterfaces.sol

- Add zeta token consumer to example contracts to show how to implement a contract without any direct interaction with ZetaToken

Integrate zeta token consumer

---

packages/addresses/package.json
packages/example-contracts/package.json
yarn.lock

Fix ci on zetachain repo

---

packages/addresses/package.json

- Update @zetachain/addresses to publish v 0.0.4

Update npm address pkg

---

packages/addresses-tools/src/addresses.helpers.ts
packages/addresses-tools/src/networks.ts
packages/addresses/src/addresses.helpers.ts
packages/example-contracts/lib/shared/network.constants.ts

- Add klaytn config to project

Add klaytn to supported networks

---

.github/workflows/release.yml

upgrade npm

---

packages/protocol-contracts/scripts/deploy-zeta-connector.ts

- Fix zeta connector deployment script

Fix zeta connector deployment scripts

---

packages/addresses-tools/src/networks.ts
packages/addresses/src/addresses.athens.json
packages/example-contracts/scripts/multi-chain-value/send-value.ts
packages/protocol-contracts/scripts/update-zeta-connector.ts

- Deploy send value to Klaytn
- Update send value script

Deploy send value contract to klaytn

---

packages/zevm-contracts/scripts/systemConstants.ts
packages/zevm-contracts/scripts/zeta-swap/stress-swap.ts

- Script to stress nodes using swap

Develop cctx testing scripts

---

packages/addresses/src/addresses.athens.json

- Deploy send contract
- Verify contract
- Update json with addresses

Deploy send contract to mumbai

---

packages/addresses-tools/package.json
packages/addresses/package.json
packages/zevm-example-contracts/package.json
packages/zevm-protocol-contracts/package.json
yarn.lock

- Publish first version of several pkg on npm
- Update version of address pkg

Publish npm packages to zetaswapv2

---

packages/addresses-tools/.npmignore
packages/addresses-tools/package.json
packages/addresses-tools/src/add-new-network.ts
packages/addresses-tools/src/log-addresses.ts

- Add prepublishonly to compile TS before publish on npm

Add prepublishonly to addressestools

---

.github/workflows/release.yml
package.json
packages/addresses-tools/package.json
packages/example-contracts/package.json
packages/interfaces/package.json
packages/protocol-contracts/package.json
packages/zeta-app-contracts/package.json
packages/zevm-example-contracts/package.json
packages/zevm-protocol-contracts/package.json

- Add prepublishOnly on every package and call it before release

Add prepublishonly to addressestools 2

---

packages/addresses-tools/.npmignore
packages/addresses-tools/package.json
packages/addresses-tools/src/index.ts

Add prepublishonly to addressestools 3

---

packages/protocol-contracts/contracts/ERC20Custody.sol

ERC20Custody contract with audit fixes.

ERC20custody contract

---

packages/addresses/package.json

- Publish address pkg v 0.0.10

Publish address 0.0.10

---

packages/addresses-tools/package.json

Release a new version of address-tools on npm

---

packages/addresses-tools/package.json
packages/addresses-tools/src/addresses.helpers.ts
packages/addresses/package.json
packages/addresses/src/addresses.athens.json
packages/zeta-app-contracts/package.json
packages/zeta-app-contracts/scripts/multi-chain-value/deploy.ts
yarn.lock

- Deploy send contracto to athens3
- Get addresses from protocol contracts repo
- Update address-tools

Deploy send contract to Athens3

---

packages/addresses/src/addresses.athens.json
packages/zeta-app-contracts/contracts/multi-chain-value/MultiChainValue.sol
packages/zeta-app-contracts/contracts/shared/IWZeta.sol
packages/zeta-app-contracts/scripts/multi-chain-value/send-value.ts

- Add sendZeta to contract
- Update send script

Add sendZeta to send contract

---

packages/zeta-app-contracts/contracts/multi-chain-value/MultiChainValue.sol
packages/zeta-app-contracts/contracts/multi-chain-value/test/ZetaConnectorMock.sol
packages/zeta-app-contracts/test/MultiChainValue.spec.ts

- Add revert handler
- Add test

Add onZetaRevert to send contract

---

packages/addresses/package.json
packages/addresses/src/addresses.helpers.ts

- Add bsc mainnet
- release an npm version

Add bsc-mainnet to addresses pkg

---

packages/zevm-app-contracts/scripts/uniswap/add-liquidity-zeta-uniswap.ts
packages/zevm-app-contracts/scripts/uniswap/remove-liquidity-zeta-uniswap.ts
packages/zevm-app-contracts/scripts/uniswap/sell-token.ts
packages/zevm-app-contracts/scripts/uniswap/sell-zeta.ts
packages/zevm-app-contracts/scripts/uniswap/uniswap.helpers.ts

- Add script to sell zeta
- Add script to sell tokens
- Add script to remove liquidity
- Add script to add liquidity

Improve uniswap scripts

---

packages/example-contracts/contracts/multi-chain-swap/MultiChainSwap.sol
packages/example-contracts/contracts/multi-chain-swap/MultiChainSwapTrident.strategy.sol
packages/example-contracts/contracts/multi-chain-swap/MultiChainSwapUniV2.strategy.sol
packages/example-contracts/contracts/multi-chain-swap/MultiChainSwapUniV3.strategy.sol
packages/example-contracts/test/MultiChainSwap.spec.ts
packages/example-contracts/test/MultiChainSwapUniswapV3.spec.ts
packages/example-contracts/test/test.helpers.ts

- Add deadline to multichain swap contract

Add deadline to uniswap v2 contract

---

.github/CODEOWNERS
packages/zevm-app-contracts/contracts/disperse/Disperse.sol
packages/zevm-app-contracts/contracts/liquidity-incentives/RewardDistributor.sol

- https://bugs.immunefi.com/dashboard/submission/25446
- https://bugs.immunefi.com/dashboard/submission/25400

implement immunefi improvements

---

packages/zeta-app-contracts/contracts/shared/ZetaEthMock.sol

- Update to support "@zetachain/protocol-contracts": "^3.0.1"

Update zetachain repo to support protocol 3.0.1

---

.github/workflows/publish-npm.yaml

feat: Npm Pkg for app contract addresses

---

.github/workflows/publish-npm.yaml

feat: npm pkg app contract addresses

---

package.json
packages/zeta-app-contracts/package.json
packages/zevm-app-contracts/package.json

Feat  npm pkg app contract addresses Part 2

feat:  npm pkg app contract addresses 2

---

.github/workflows/publish-npm.yaml

feat: npm pkg app contract addresses 3

---

packages/zevm-app-contracts/contracts/disperse/Disperse.sol
packages/zevm-app-contracts/data/addresses.json

Add event to disperse to use goldsky
new address: 0xf394dc01879E39f19eDA533EFD10C82eEee5B2b1

feat: Add events to disperse

---

package.json
packages/zeta-app-contracts/arguments.js
packages/zeta-app-contracts/data/addresses.json
packages/zeta-app-contracts/hardhat.config.ts
packages/zeta-app-contracts/package.json
packages/zeta-app-contracts/scripts/multi-chain-value/send-value.ts
packages/zevm-app-contracts/arguments.js
packages/zevm-app-contracts/hardhat.config.ts
packages/zevm-app-contracts/package.json
packages/zevm-app-contracts/scripts/address.helpers.ts
packages/zevm-app-contracts/scripts/disperse/deploy.ts
packages/zevm-app-contracts/scripts/liquidity-incentives/deploy.ts
packages/zevm-app-contracts/scripts/zeta-points/deploy.ts
packages/zevm-app-contracts/scripts/zeta-swap/deploy.ts

- Many tiny updates needed to currently support mainnet scripts

feat: Update repo to support mainnet

---

README.md

feat: Rename the zeta chainzetachain repo

---

.github/CODEOWNERS

- Add Hernan Carrizo as codeowner for app sc

feat: Add Hernan Carrizo as codeowner for app sc

---

packages/zeta-app-contracts/package.json
packages/zevm-app-contracts/package.json

feat: publish npm

---

packages/zevm-app-contracts/package.json

feat: Update npm to add proof of liveness addresses
